---
- hosts: all:!ossim-server:!clamav-repo
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    rsyslog_server: 192.168.254.254
    clamav_repo: clamav.local
    package_clamav: clamav-0.99.2-1.el7.x86_64.rpm
    package_clamav_data: clamav-data-0.99.2-1.el7.noarch.rpm
    package_clamav_devel: clamav-devel-0.99.2-1.el7.x86_64.rpm
    package_clamav_filesystem: clamav-filesystem-0.99.2-1.el7.noarch.rpm
    package_clamav_lib: clamav-lib-0.99.2-1.el7.x86_64.rpm
    package_clamav_scanner: clamav-scanner-0.99.2-1.el7.noarch.rpm
    package_clamav_scanner_systemd: clamav-scanner-systemd-0.99.2-1.el7.noarch.rpm
    package_clamav_server: clamav-server-0.99.2-1.el7.x86_64.rpm
    package_clamav_server_systemd: clamav-server-systemd-0.99.2-1.el7.noarch.rpm
    package_clamav_update: clamav-update-0.99.2-1.el7.x86_64.rpm
    package_keyutils_libs_devel: keyutils-libs-devel-1.5.8-3.el7.x86_64.rpm
    package_krb5_devel: krb5-devel-1.14.1-27.el7_3.x86_64.rpm
    package_libcom_err_devel: libcom_err-devel-1.42.9-9.el7.x86_64.rpm
    package_libkadm5: libkadm5-1.14.1-27.el7_3.x86_64.rpm
    package_libselinux_devel: libselinux-devel-2.5-6.el7.x86_64.rpm
    package_libsepol_devel: libsepol-devel-2.5-6.el7.x86_64.rpm
    package_libverto_devel: libverto-devel-0.2.5-4.el7.x86_64.rpm
    package_nmap_ncat: nmap-ncat-6.40-7.el7.x86_64.rpm
    package_openssl_devel: openssl-devel-1.0.1e-60.el7_3.1.x86_64.rpm
    package_pcre_devel: pcre-devel-8.32-15.el7_2.1.x86_64.rpm
    package_zlib_devel: zlib-devel-1.2.7-17.el7.x86_64.rpm
  tasks:
  - name: Copy {{item}} rpm file to server
    copy:
      src: packages/{{item}}
      dest: /tmp/{{item}}
    with_items:
      - "{{ package_clamav }}"
      - "{{ package_clamav_data }}"
      - "{{ package_clamav_devel }}"
      - "{{ package_clamav_filesystem }}"
      - "{{ package_clamav_lib }}"
      - "{{ package_clamav_scanner }}"
      - "{{ package_clamav_scanner_systemd }}"
      - "{{ package_clamav_server }}"
      - "{{ package_clamav_server_systemd }}"
      - "{{ package_clamav_update }}"
      - "{{ package_keyutils_libs_devel }}"
      - "{{ package_krb5_devel }}"
      - "{{ package_libcom_err_devel }}"
      - "{{ package_libkadm5 }}"
      - "{{ package_libselinux_devel }}"
      - "{{ package_libsepol_devel }}"
      - "{{ package_libverto_devel }}"
      - "{{ package_nmap_ncat }}"
      - "{{ package_openssl_devel }}"
      - "{{ package_pcre_devel }}"
      - "{{ package_zlib_devel }}"
  - name: install ClamAV
    yum:
      name: /tmp/{{item}}
      state: present
    with_items:
      - "{{ package_clamav }}"
      - "{{ package_clamav_data }}"
      - "{{ package_clamav_devel }}"
      - "{{ package_clamav_filesystem }}"
      - "{{ package_clamav_lib }}"
      - "{{ package_clamav_scanner }}"
      - "{{ package_clamav_scanner_systemd }}"
      - "{{ package_clamav_server }}"
      - "{{ package_clamav_server_systemd }}"
      - "{{ package_clamav_update }}"
      - "{{ package_keyutils_libs_devel }}"
      - "{{ package_krb5_devel }}"
      - "{{ package_libcom_err_devel }}"
      - "{{ package_libkadm5 }}"
      - "{{ package_libselinux_devel }}"
      - "{{ package_libsepol_devel }}"
      - "{{ package_libverto_devel }}"
      - "{{ package_nmap_ncat }}"
      - "{{ package_openssl_devel }}"
      - "{{ package_pcre_devel }}"
      - "{{ package_zlib_devel }}"
  - name: Run the command for enable antivirus_can_scan_system
    command: setsebool -P antivirus_can_scan_system 1
  - name: Run the command for enable antivirus_use_jit
    command: setsebool -P antivirus_use_jit 1
  - name: Copy systemd services file to server
    copy:
      src: systemd/{{item}}
      dest: /lib/systemd/system/{{item}}
    with_items:
     - clam-freshclam.service
     - clamd.service
     - clamd@scan.service
  - name: ensure log file exists
    copy:
      content: ""
      dest: /var/log/clamd.log
      force: no
      group: clamscan
      owner: root
      mode: 0664
  - name: write the freshclam config file
    template:
      src: configs/freshclam.j2
      dest: /etc/freshclam.conf
      owner: root
      group: root
      mode: 0644
    notify:
     - restart clam-freshclam
  - name: write the clamd config file
    template:
      src: configs/clamd.j2
      dest: /etc/clamd.d/clamd.conf
      owner: root
      group: root
      mode: 0644
    notify:
     - restart clamd@scan
  - name: ensure clam-freshclam is running
    service:
      name: clam-freshclam
      state: started
      enabled: yes
  - name: ensure clamd@scan is running
    service:
      name: clamd@scan
      state: started
      enabled: yes
  - name: Creates schedule scan cronjob
    cron: minute="20" hour="3"
          name="Schedule scan (daily schedule)"
          cron_file="clamscan-Daily"
          user="root"
          job="clamdscan -i -c /etc/clamd.d/clamd.conf /*"
  - name: write the rsyslog config file
    template:
      src: configs/rsyslog.j2
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: 0644
    notify:
     - restart rsyslog
  - name: ensure rsyslog is running
    service:
      name: rsyslog
      state: started
      enabled: yes
  handlers:
    - name: restart clam-freshclam
      service:
        name: clam-freshclam
        state: restarted
    - name: restart clamd@scan
      service:
        name: clamd@scan
        state: restarted
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
